#        _    _      _
#      | |  | |    | |
#   ___| |__| | ___| |_ __   ___ _ __
#  / _ \  __  |/ _ \ | '_ \ / _ \ '__|
# |  __/ |  | |  __/ | |_) |  __/ |
#  \___|_|  |_|\___|_| .__/ \___|_|
#                    | |
#                    |_|
# Made by CandiesJar | https://discord.gg/dJ8DG2cSzt
# BungeeCord config file

settings:

  # Used by the plugin developer for debugging purposes.
  # It will enable various debug components in the plugin.
  # Enable only if told by the developer.
  debug: false

  # Method used by the plugin to check server status
  # DEFAULT: Simple ping check with BungeeCord API.
  # SOCKET: Uses Java socket API to check server status.
  # WARNING: Change ONLY if you're facing issues.
  ping_mode: "DEFAULT"

  # Decide if the updater should be enabled.
  updater: true

  # Enable telemetry, this will send anonymous data to the developer.
  #
  telemetry: true

commands:

  reload:
    permission: "ehelper.reload"

  debug:
    permission: "ehelper.debug"

  backup:
    enabled: true
    permission: "ehelper.backup"

  info:
    enabled: true
    permission: "ehelper.info"

